### ISSUE TITLE
Focus on Input

### ISSUE THREAD

**Issue by chadwhitaker** [driftyco/cordova-plugin-wkwebview-engine#1]
Currently, you can use the javascript `.focus()` method on an input text box to focus on the input and trigger the keyboard open. 

Note that it does require the follow preference in the config.xml:
```
<preference name="KeyboardDisplayRequiresUserAction" value="false" />
```

This functionality doesn't work with enabling WKWebView.

**Comment by ghenry22** [comment]
This fork of the original repo has a commit to make it obey the keyboarddisplayrequiresuseraction value, might not be relevant but just came across it looking through the different available forks.

https://github.com/kshaaban-/cordova-plugin-wkwebview-engine/commit/52093ffe1e965b2607fac90480bfb0a4e0ac90f8

**Comment by manucorporat** [comment]
This is a known issue: https://issues.apache.org/jira/browse/CB-10376
If the base [wkwebview repo](https://github.com/apache/cordova-plugin-wkwebview-engine) does not merge the fix, I think we should try to find a solution that fits in this fork.

what do you think @shazron?

I will keep this issue open!

**Comment by shazron** [comment]
We would like to pull this in, as the issue says, waiting for the PR :)

**Comment by manucorporat** [comment]
@shazron thanks! I am closing this issue. Any future conversation should continue in JIRA.
