### ISSUE TITLE
Safari technology preview creates pink flickering

### ISSUE THREAD

**Issue by mnewmedia** [driftyco/cordova-plugin-wkwebview-engine#10]
Safari technology preview debugger creates pink flickering on screen. Maybe not important but just to note. If you dont care feel free to close ;)

**Comment by manucorporat** [comment]
It might be because it is highlighting the selected DOM element?

**Comment by mnewmedia** [comment]
Nope. Looks really like strange flickering. And it does not behave like this in uiwebview.






On Fri, Aug 19, 2016 at 1:03 PM +0200, "Manu Mtz.-Almeida" <notifications@github.com> wrote:












It might be because it is highlighting the selected DOM element?

**Comment by jgw96** [comment]
Hello @mnewmedia ! Thanks for opening an issue with us. Would you mind checking the paintbrush to see if it is blue ?
<img width="190" alt="screen shot 2016-08-19 at 10 26 12 am" src="https://cloud.githubusercontent.com/assets/8823093/17813029/3cd331ea-65ef-11e6-8a77-dc3a2696251d.png">
If it is blue this means that paint flashing is turned on, which will cause a flash everytime the browser runs the `paint` process. Thanks!

**Comment by mnewmedia** [comment]
You where right.
