### ISSUE TITLE
after upgrade app is crashing when entering background

### ISSUE THREAD

**Issue by kabus202** [driftyco/cordova-plugin-wkwebview-engine#100]
Hi,

im getting the following error after entering background mode:

017-02-24 15:59:16.569903 core[17405:4486648] Disconnected from FCM
[DEBUG] Did enter background
[DEBUG] Did close IPv6 listening socket 10
[DEBUG] Did close IPv4 listening socket 9
[INFO] GCDWebServer stopped

  GWS_DCHECK(_options == nil);  // The server can never be dealloc'ed while running because of the retain-cycle with the dispatch source

is this a known issue?

Regards,
kab

**Comment by kabus202** [comment]
Workaround is: 

`ionic plugin add cordova-plugin-wkwebview-engine@1.1.1`

**Comment by kabus202** [comment]
could possibly be related to this:

[https://github.com/swisspol/GCDWebServer/pull/292/commits/f45963007ba383aa570241eaa9914dc00a36524d](https://github.com/swisspol/GCDWebServer/pull/292/commits/f45963007ba383aa570241eaa9914dc00a36524d)

**Comment by agarcia17** [comment]
yeah same here

**Comment by madubois** [comment]
Same problem here! It's a real problem for my user...

**Comment by gabrielbazan7** [comment]
same here

**Comment by loqoio** [comment]
same here :)

**Comment by pensan** [comment]
I would appreciate a fix too

**Comment by Dema1348** [comment]
same problem here :C

**Comment by gabrielbazan7** [comment]
This is working ok: 
```https://github.com/driftyco/cordova-plugin-wkwebview-engine.git#4221015eb3f309fe593a7d81205b691e27088743 ```

**Comment by pensan** [comment]
@gabrielbazan7 suggestion prevents the app from crashing, but "PATCH" xhr request are not working anymore (CORS), "GET" is working fine.

**Comment by michaelpeterlee** [comment]
For the interim, edit GCDWebServer.m:

_suspendInBackground = [_GetOption(_options, GCDWebServerOption_AutomaticallySuspendInBackground, @NO) boolValue];

**Comment by michaelpeterlee** [comment]
On resume from iOS lock screen, all local user file resources are unavailable: 
"Failed to load resource: Could not connect to the server. http://localhost:8080/var/.."

**Comment by michaelpeterlee** [comment]
NOTE: Resume from User app-switching responds differently for each of the following scenarios:

1. Run from Xcode
1.1. Debug cable attached - App freezes as per @kabus202.
1.2. Debug cable detached - App resumes by reinitialising completely
2. Testflight - App local user file resources are unavailable:
"Failed to load resource: Could not connect to the server. http://localhost:8080/var/.."

**Comment by michaelpeterlee** [comment]
Add key to your XCode project -info.plist 'Application does not fun in background' = YES.

**Comment by madubois** [comment]
I tried to add in Xcode projet -info.plist Application does not run in background' = YES
but it's not working. can you copy paste the full key exemple?

**Comment by michaelpeterlee** [comment]
![image](https://cloud.githubusercontent.com/assets/19398181/23722190/63baf5c8-04a9-11e7-8109-660dac09b5a7.png)

**Comment by madubois** [comment]
I have identical config but it's doesn't work...

**Comment by michaelpeterlee** [comment]
We are using https://github.com/driftyco/cordova-plugin-wkwebview-engine/commit/4221015eb3f309fe593a7d81205b691e27088743, have not tested that setting with latest master.

**Comment by hkbenchan** [comment]
Seems that 3e6840d0ec5395e768932d5a3c469558e5f6e1eb is working for me, others?

**Comment by kabus202** [comment]
Yep, I can confirm that it's working with the master.
