### ISSUE TITLE
WKWebView returns by default on main page of the app resuming from background/sleep - iOS

### ISSUE THREAD

**Issue by dspachos** [driftyco/cordova-plugin-wkwebview-engine#103]
Every time the app gets the focus it returns by default to the home page.
Steps to re-produce (tested on iOS only):
- Create a simple Ionic 2 app and use the WKWebView. The app must have at least 2 views
- Open the app in iOS, go to the 2nd view (not the home page-view)
- Press the home button and open another app
- Press the home button twice and select the Ionic 2 app
- It returns by default to the home page view

This behaviour is not observed when using the UIWebView

**Comment by madubois** [comment]
It's seem to be the same bug : https://github.com/driftyco/cordova-plugin-wkwebview-engine/issues/100

**Comment by michaelpeterlee** [comment]
On resuming from background/sleep, the app initialises entirely so will display your default view.

**Comment by dspachos** [comment]
Thanks for the tip.
The [4221015](https://github.com/driftyco/cordova-plugin-wkwebview-engine/commit/4221015eb3f309fe593a7d81205b691e27088743) is not working for me: the app stays freeze in the splash screen forever. My config.xml has the code:
```
<allow-navigation href="http://localhost:8080/*"/>
<feature name="CDVWKWebViewEngine">
  <param name="ios-package" value="CDVWKWebViewEngine" />
</feature>

<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
```

Is there any other way to prevent initialisation every time the app gets the focus?

**Comment by michaelpeterlee** [comment]
We have to reinitialise the app to get GCDWebServer to play nice. To further complicate matters, development scenarios differ from production, so we apply the following XCode project setting:

Add key to your XCode project -info.plist 'Application does not run in background' = YES.

**Comment by silviogutierrez** [comment]
@dspachos : in 4221015, you need to whitelist ionic.local, not localhost.

I just play safe and do:

```xml
    <plugin name="cordova-plugin-wkwebview-engine" spec="https://github.com/driftyco/cordova-plugin-wkwebview-engine.git#4221015eb3f309fe593a7d81205b691e27088743" />

    <allow-navigation href="*" />
    <allow-navigation href="http://ionic.local/*" />
    <allow-navigation href="http://localhost:8080/*" />
    <feature name="CDVWKWebViewEngine">
        <param name="ios-package" value="CDVWKWebViewEngine" />
    </feature>
    <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
```

Note that I use the wildcard for some other external scripts. ionic.local should suffice. And localhost in case I upgrade later. Hope that helps.

**Comment by dspachos** [comment]
Thanks for the tips, @silviogutierrez suggestions solved the issue. 

I've noticed that, if I add the key 'Application does not run in background' = YES, as @michaelpeterlee suggested, then the app initialises again in every resume - so I removed it from my plist file.

My final question is, related to comment @michaelpeterlee's comment: is it safe to use it for production?

**Comment by michaelpeterlee** [comment]
We are using https://github.com/driftyco/cordova-plugin-wkwebview-engine/commit/4221015eb3f309fe593a7d81205b691e27088743, have not tested that setting with latest master.

We are in final BETA with this and intend to release tomorrow. One behaviour we note, sometimes on User initiated sleep/resume the app will not restart however our custom GCDWebServer (to serve video only) web-server is available.

**Comment by ghenry22** [comment]
I am using this plugin at the latest commit before the local proxy updates as listed above.  It's live in the app store and works pretty well.  I haven't started testing with the updated local proxy solution yet as it seems to have a few issues like this one.

**Comment by manucorporat** [comment]
This bug was fixes: https://github.com/driftyco/cordova-plugin-wkwebview-engine/issues/100

Please feel free to reopen if you feel like it was not

**Comment by HartHerbert** [comment]
Still happening on my app with wkwebview. When I enter the app and then leave the app by homebutton or open another one and return to the app, the local server restarts (So also my app restarts). Still an issue using `version="1.1.4-dev"`
