### ISSUE TITLE
localStorage lost after updating from WK 2.0 to WK 3.0

### ISSUE THREAD

**Issue by uaza** [driftyco/cordova-plugin-wkwebview-engine#106]
Is this a bug or accepted behaviour like #28?

**Comment by kristfal** [comment]
@uaza Could be either, but you shouldn't use localStorage at all in iOS as it can be wiped by the system in case it decides that it needs more space (from experience, any device with less than 1/3 free space could be wiped).

I suggest you have a look at [Cordova Native Storage](https://github.com/TheCocoaProject/cordova-plugin-nativestorage).

**Comment by samastur** [comment]
Native Storage has been very problematic for us. All crashes of our app on IOS come from failure in this plugin and quality control on it is pretty questionable (2.2 reliably triggered syntax error on start).

**Comment by uaza** [comment]
Ok, thank you for your answers, I close this issue.
