### ISSUE TITLE
App crashes when running without livereload

### ISSUE THREAD

**Issue by leschirmeur** [driftyco/cordova-plugin-wkwebview-engine#11]
Hi there,

after installing the plugin (ionic v1) we can start our app using livereload but no images are shown. This is however not the issue I am raising here. When running the app without livereload, the app crashes after a few seconds running on a device or in the simulator.

This does not happen when running on iOS8, only iOS9 - which stresses the fact that it is caused by the WKWebView plugin.

Error message shown in XCode:

2016-08-19 12:53:50.021 Wild Table[14578:448057] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000106bd5d85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010657adeb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000106a8ea52 -[__NSPlaceholderArray initWithObjects:count:] + 290
	3   CoreFoundation                      0x0000000106aeb0b4 +[NSArray arrayWithObjects:count:] + 52
	4   Wild Table                          0x00000001032dc1ea -[CDVWKWebViewEngine quoteString:] + 138
	5   Wild Table                          0x00000001032dbf98 __43-[CDVWKWebViewEngine sendXHRResponse:path:]_block_invoke + 312
	6   Foundation                          0x00000001061ed630 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	7   Foundation                          0x0000000106128805 -[NSBlockOperation main] + 101
	8   Foundation                          0x000000010610b725 -[__NSOperationInternal _start:] + 646
	9   Foundation                          0x000000010610b336 __NSOQSchedule_f + 194
	10  libdispatch.dylib                   0x000000010994d3eb _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x000000010993382c _dispatch_queue_drain + 2215
	12  libdispatch.dylib                   0x0000000109932d4d _dispatch_queue_invoke + 601
	13  libdispatch.dylib                   0x0000000109935996 _dispatch_root_queue_drain + 1420
	14  libdispatch.dylib                   0x0000000109935405 _dispatch_worker_thread3 + 111
	15  libsystem_pthread.dylib             0x0000000109c8a4de _pthread_wqthread + 1129
	16  libsystem_pthread.dylib             0x0000000109c88341 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by manucorporat** [comment]
thanks for the report. I am working in a fix + more useful debug messages.

**Comment by manucorporat** [comment]
@leschirmeur @uaza this commit should fix the crash and provide better error handling and debugging.

Still WIP though ;)

**Comment by manucorporat** [comment]
@leschirmeur  can you reinstall the plugin? and try again?

**Comment by jgw96** [comment]
@leschirmeur Would you mind giving it another try? Thanks!

**Comment by leschirmeur** [comment]
Trying to squeeze it in, need a couple days though as work schedule for a client is tight right now

**Comment by leschirmeur** [comment]
@manucorporat Alright, tried again and crash has gone, thank you! Closing this issue and will move on to the next one :-)
