### ISSUE TITLE
Install Error: The header content contains invalid characters

### ISSUE THREAD

**Issue by verylongword** [driftyco/cordova-plugin-wkwebview-engine#114]
I have tried for days, but my attempts to run the Ionic2 blank template on osX El Capitan,
Deploying to iPhone-SE,  10.2  simulator or iPhone 7 Plus always result in 
** BUILD SUCCEEDED **
followed by the "white screen of death"
   Seems the world is NOT my oyster.

So I tried Apache Cordova WKWebView plugin, with the same result, but got an additional error:
      Installing "cordova-plugin-wkwebview-engine" for ios
      Error: The header content contains invalid characters

This is my first encounter with a Mac, and things look grim !!!
I have an Ionic2  app published in the Android App Store, so my problems seem to be entirely to do with osX.

 My most recent (failed) attempt:
In a Terminal:

cd /Users/apple/Desktop/don/ionic2
ionic start Test blank --v2
cd Test
ionic platform add ios
ionic prepare ios
ionic emulate ios --consolelogs
ionic plugin rm cordova-plugin-wkwebview-engine
ionic plugin add https://github.com/driftyco/cordova-plugin-wkwebview-engine.git â€”save
	â€”> Installing "cordova-plugin-wkwebview-engine" for ios
		â€”> Error: The header content contains invalid characters
ionic prepare ios

LAUNCH XCODE from/Users/apple/Desktop/don/ionic2/Test/platform/ios/.xcodeproj
In xCode: Run on simulator 
 --->  "white screen of death"

Any help much appreciated:  How to get ANY ionic2 project to run on ANY iPhone simulator ???
Maybe other people have the same dreadful problem.
Don

**Comment by manucorporat** [comment]
```
ionic plugin add https://github.com/driftyco/cordova-plugin-wkwebview-engine.git â€”save
```

I think you are entering the command incorrectly... use:
```
ionic plugin add https://github.com/driftyco/cordova-plugin-wkwebview-engine.git --save
```
