### ISSUE TITLE
wkwebview will fail if server not allow cors.

### ISSUE THREAD

**Issue by JiaLiPassion** [driftyco/cordova-plugin-wkwebview-engine#124]
The issue has been discussed in #3, and other issues, in wkWebview plugin 3.0, we have a local web server options to resolve origin is null issue, but if server not support CORS, we still fail to send any requests to server.

**Comment by manucorporat** [comment]
So, CORS in enforced by WKWebView which is a dynamic library provided by Apple. We can't nothing about it.

You have two options:

1. Implement CORS in your server
2. Use the native HTTP plugin: http://ionicframework.com/docs/native/http/
This plugin will use native code to perform the request, bypassing this way the CORS checks.
