### ISSUE TITLE
XMLHttpRequest withCredentials

### ISSUE THREAD

**Issue by danielehrhardt** [driftyco/cordova-plugin-wkwebview-engine#132]
**Ionic version:**  (check one with "x")
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[X ] bug report

**Current behavior:**
i try to add the wkwebview to my ionic application but i have a problem with XMLHttpRequest with Credentials in the header i got a 401 error from my server 
`Failed to load resource: the server responded with a status of 401 (HTTP/2.0 401)`
cors is enabled at the api

my http request headers
```
 this.headers = new Headers({ 'X-Requested-With': 'XMLHttpRequest' });
 this.requestOptions = new RequestOptions({ headers: this.headers, withCredentials: true });
```

**Comment by manucorporat** [comment]
can you log/inspect the request/response from the server side?

**Comment by danielehrhardt** [comment]
i think i have the cookie Problem.

https://github.com/driftyco/cordova-plugin-wkwebview-engine/issues/23
