### ISSUE TITLE
[Cordova 7.0.0] WARN: wkRewriteURL is deprecated, use normalizeURL instead

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/cordova-plugin-wkwebview-engine#134]
Hi,

Honestly I'm not sure if that Xcode warning comes from the cordova-plugin-wkwebview-engine plugin, but thought I better report it since it begins with "wk....". So after the upgrade to Cordova 7.0.0, Xcode log following warning:

    WARN: wkRewriteURL is deprecated, use normalizeURL instead

Just in case.

Thx and best regards

P.S.:  @manucorporat I don't want to spam you with such msg, for the future you rather like that I/we report such Xcode warning or it isn't necessary?

**Comment by mtshare** [comment]
Same for me

**Comment by manucorporat** [comment]
Fixed in latest!
