### ISSUE TITLE
HTTP Request Origins set to LocalHost

### ISSUE THREAD

**Issue by ehorodyski** [driftyco/cordova-plugin-wkwebview-engine#137]
This plugin looks like it changes the HTTP request `origin` header from `file://` to `localhost:8080`. This is breaking a lot of calls I'm trying to make to APIs that are not CORS enabled, and do not whitelist `localhost` as an entry.

Can anyone provide some insight?

**Comment by manucorporat** [comment]
It is not possible to bypass CORS in WKWebView. You have to implement CORS in your server whitelisting localhost or you can use the HTTP cordova plugin https://ionicframework.com/docs/native/http/

I recommend to implement CORS in your server though

**Comment by JiaLiPassion** [comment]
Hi , Mr. Manu MA

Could you check my PR,
https://github.com/driftyco/cordova-plugin-wkwebview-engine/pull/115, is it
the correct direction?

thanks .

Jia Li

**Comment by ehorodyski** [comment]
@manucorporat -- Would it come into consideration to let consumers decide to mask their origins, from `null` or `localhost` to something configurable?

There are many APIs available that are not CORS enabled that this plugin is preventing us from using. When building for web there's many options to proxy to mask `localhost` as origin, but we've found a lot of 3rd party APIs we want to use are blocking based on origin. 

Then it's like, do we drop the plugin, and lose the latest web advances (like `display:sticky` in some cases, and Ionic's infinite scroll), or try to create a wrapper around an API, congesting the end-user.

Is there a win-win scenario where I can call Yelp and have Ionic Sticky Headers too?
