### ISSUE TITLE
Is there a possibility to add a fallback to UIWebView for <iOS 9 devices?

### ISSUE THREAD

**Issue by nickkenens** [driftyco/cordova-plugin-wkwebview-engine#14]
Title says it all, just a question.

Since 10% of devices are still running iOS 8, it would be nice.
source: https://developer.apple.com/support/app-store/

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! This behavior actually already exists in this plugin! If it is running on a device running ios 8 it will fall back to uiwebview since wkwebview does not work well on ios8. Thanks!

**Comment by manucorporat** [comment]
@jgw96 is right!
since this plugin is just a incremental fork of https://github.com/apache/cordova-plugin-wkwebview-engine#notes it fallback to UIWebView

we are going to update our README to reflect that.

Thanks for opening the issue!

**Comment by jgw96** [comment]
@nickkenens I just committed a tiny edit to our readme to make this more clear. Thanks!

**Comment by nickkenens** [comment]
@jgw96 thanks for the clarification!
