### ISSUE TITLE
Leaving/Entering foreground causes entire web view reload

### ISSUE THREAD

**Issue by NorthMcCormick** [driftyco/cordova-plugin-wkwebview-engine#16]
As my app leaves the foreground and comes back to the foreground it looks like the entire app is reloaded which is problematic because then the user always ends up at the home page instead of whatever they were doing.

I'm kind of surprised no one else has noted this, making me think it *might* just be me.

Here are the logs I get

```
--- This is when I go to the iOS home screen ---
 
Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.
 
--- This is once I tap the app to bring it back to the foreground, not closing it, just resuming ---

2016-08-19 17:21:08.178 RedFit[91023:9574005] CDVWKWebViewEngine reloading!
2016-08-19 17:21:08.186 RedFit[91023:9574005] IAB.close() called but it was already closed.
```

I will continue testing to see if I can find any solutions or similar issues linked to Cordova's branch

**Comment by NorthMcCormick** [comment]
Wow not more than 30 seconds after posting this a seemingly out of this world fix fixed it.

Apparently they rely on the title tag to assume if the WK engine has crashed or not. So, having an empty title tag made the system assume that it had crashed and asked it to reload.

This seems totally weird but I'm sure they wouldn't have opted for that if there was another way hahaha.

https://github.com/apache/cordova-plugin-wkwebview-engine/pull/11

This is where I saw them discussing it, gave it a try, it works.

Just make sure your app has something in the <title> tags, maybe we could add that to the readme as an install step so people don't stress when their apps don't hold their states.

**Comment by manucorporat** [comment]
@NorthMcCormick hi! interesting! I didn't know it
can you explain: "Just make sure your app has something in the tags" a little bit more ?

I totally  agree we should add something in the README

**Comment by NorthMcCormick** [comment]
Yeah it was a very odd fix haha.

I just had `<title></title>` originally (not sure if this is by default in an ionic project or if I had emptied it) and changed it to `<title>RedFit</title>` and that fixed it.

**Comment by gmooren** [comment]
@NorthMcCormick nice catch. Saved me hours of debugging.

**Comment by cvaliere** [comment]
@NorthMcCormick you're a genius

**Comment by shazron** [comment]
Fix: https://github.com/apache/cordova-plugin-wkwebview-engine/pull/16

**Comment by ammichael** [comment]
@NorthMcCormick 

Sorry, but where am I supposed to add the title tag? I added to my view and didn't help =(

I also applied @shazron's fix, still didn't help

**Comment by danielcrk-cn** [comment]
@NorthMcCormick, are you talking about the title tag in index.html? I'm experiencing the exact same behaviour as you, the WKWebView reloads when the app resumes, but my title tag is not empty (it's <title>Ionic</title> as per default)

**Comment by acurrieclark** [comment]
This is an excellent catch. Thanks for sharing @NorthMcCormick

**Comment by NorthMcCormick** [comment]
@danielcrk-cn Yes, I am not sure what else would cause the reload. I'd just check that your tag is valid and that none of your build steps are overwriting it or removing it (or any code in your app for that matter).

@ammichael It's the <title></title> tag in your index.html of your app. If you use different html pages that have <title> tags make sure they all have values too (if you're using Ionic you should only have the one in the index.html).

**Comment by danielcrk-cn** [comment]
@NorthMcCormick I'm sorry, you were totally right. Turned out Ionic 2 was changing the title during runtime. Everything sorted now. Thanks for you help!
