### ISSUE TITLE
switching pages is slower than in UIWebview / Black animation

### ISSUE THREAD

**Issue by mnewmedia** [driftyco/cordova-plugin-wkwebview-engine#17]
Switching between pages is slower than in UIWebview. I'm using ionic 1 with sidemenu when i select another page the current menupoint is highlighted in blue and also the new menu i press gets highlighted in blue, it stays like this for like 1-2 second before closing the menu and going to the new page.

Also when switching pages there is sometimes a black flickering / black animation. (Could be that those 2 issues hangs togheter, and because of can't loading the animation, it responses slow..)

Maybe it's also a bit slow because of all the XHR interceptions to all templates like for example`templates/filter/item.html`

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0-beta.35
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.12.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by manucorporat** [comment]
@mnewmedia hi!

does it happen the first time only right? angular 2 should cache the template so it does not have to requested them more than once.

> Maybe it's also a bit slow because of all the XHR interceptions to all templates like for exampletemplates/filter/item.html

probably yes. A "real" XHR to file (like it was in UIWebView) is probably a very optimized operation.

Fortunately, there are still a lot of optimization strategies we can try to make this faster.
- We can even prefetch templates in RAM (based in previous app usage).
- Optimize [self quoteString:] function
- Optimize memory allocation
- Optimize JS side

Right now, we just wanted something that worked as better as possible.

Also, making the XHR bypass faster will not matter once "offline compiling" is done.
**offline compiling** will compile your HTML templates into JS code at comping time, so angular will not even perform any XHR! Once this is done, initial loading and switching pages will be instant.

We are working closely with the angular team at google to make this a reality! 
Check out:
https://github.com/driftyco/ionic/commits/deeplinks-ngmodule
https://github.com/driftyco/ionic/issues/6776

In the meantime, you can inline your templates in your JS so you save XHR requests or you can actively help us making this plugin faster!
