### ISSUE TITLE
Unable to use sliding items

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/cordova-plugin-wkwebview-engine#18]
This is the most awesome WKWebView plugin I ever found (so fast) but I just can't seem to use sliding items (sliding won't even start, as if not present).

iOS 10
Cordova iOS 4.1.0

**Comment by manucorporat** [comment]
@Bouzmine I have tested WKWebView with [ionic-conference-app](https://github.com/driftyco/ionic-conference-app) which features several sliding items and they work as expected...

can you provide a full repo that reproduces the issue?
are you sure it worked with UIWebView?

**Comment by Bouzmine** [comment]
I can confirm it works on UIWebView. Here is my project's repo : github.com/Bouzmine/metho

**Comment by manucorporat** [comment]
@Bouzmine I tried to use your repo.

Several issues:

1. Do not use "^" in package.json since it means greater than:
So `    "@angular/core": "^2.0.0-rc.4",` is downloading 2.0.0-rc.5. That can cause a lot of troubles since most of the time there are not compatible releases.

 ```json
  "dependencies": {
    "@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/forms": "0.2.0",
    "@angular/http": "2.0.0-rc.4",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/router": "2.0.0-rc.2",
    "deepcopy": "^0.6.3",
    "es6-shim": "0.35.0",
    "ionic-angular": "2.0.0-beta.11",
    "ionic-native": "^1.3.5",
    "ionicons": "3.0.0",
    "moment": "^2.13.0",
    "ng2-translate": "2.2.2",
    "numeral": "^1.5.3",
    "pouchdb": "^5.4.4",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "0.6.12"
  },
```

2. Some typescript errors are preventing `ionic serve` to generate `app.bundle.js`
```
TypeScript error: /Users/manualmeida/Downloads/metho-master/app/pages/settings/settings.ts(13,27): Error TS2307: Cannot find module 'deepcopy'.
TypeScript error: /Users/manualmeida/Downloads/metho-master/app/providers/advanced-mode/advanced-mode.ts(19,18): Error TS2339: Property 'cordova' does not exist on type 'Window'.
TypeScript error: /Users/manualmeida/Downloads/metho-master/app/providers/advanced-mode/advanced-mode.ts(39,52): Error TS2339: Property 'cordova' does not exist on type 'Window'.
TypeScript error: /Users/manualmeida/Downloads/metho-master/app/providers/app-storage/app-storage.ts(7,26): Error TS2307: Cannot find module 'pouched'.
```

can you fix them? let me know when it is done! I will try again

**Comment by Bouzmine** [comment]
@manucorporat Fixed. Thanks for the hints, I had been wondering for a while why it wouldn't `git clone` and `npm install` properly. The `^` was the key. I fixed the TypeScript errors for cleanness but they weren't blocking `app.bundle.js` from being created (it was the poor dependencies which were).

**Comment by Bouzmine** [comment]
@manucorporat why did you close this issue?

**Comment by manucorporat** [comment]
@Bouzmine sorry! Reopened

**Comment by manucorporat** [comment]
@Bouzmine I can't reproduce in Simulator

![aug-21-2016 17-39-52](https://cloud.githubusercontent.com/assets/127379/17838170/59c341ae-67c6-11e6-8735-4100f2427893.gif)

**Comment by ghenry22** [comment]
sliding items are working fine in my project with this wk webview plugin also.

**Comment by Bouzmine** [comment]
@manucorporat Removed and added the plugin again and now it's working. Sorry for the inconvenience.
