### ISSUE TITLE
Camera plugin stopped working after updating to wkwebview

### ISSUE THREAD

**Issue by vikramk0901** [driftyco/cordova-plugin-wkwebview-engine#19]
Camera plugin stops working after updating to wkwebview. (http://ionicframework.com/docs/v2/native/camera/). getPicture function is not being triggered

iOS 9.2
Cordova

**Comment by manucorporat** [comment]
@vikramk0901 Hi, can you provide more information?
Any JS log or native log (from Xcode)

**Comment by vikramk0901** [comment]
ERROR: Plugin 'Camera' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.

What am I missing here ?

**Comment by vikramk0901** [comment]
I got it working. I removed ios platform and deleted ios.json. (sorry for the trouble)

Keep up the good work.

**Comment by manucorporat** [comment]
@vikramk0901 how did you fixed it? it my help another developers

**Comment by vikramk0901** [comment]
@manucorporat I just rebuilt the whole thing again. There was some conflict in my ios.json
