### ISSUE TITLE
OS X install error

### ISSUE THREAD

**Issue by Kobzol** [driftyco/cordova-plugin-wkwebview-engine#2]
Executing `ionic plugin add https://github.com/driftyco/cordova-plugin-wkwebview-engine.git --save` on OS X gives this error: Error: Unexpected token } in JSON at position 3185.

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.2.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind posting the whole error here? Also, can you update your Ionic cli by running `npm install -g ionic` ? It looks you may be running a slightly older version. Finally, could you try with cordova plugin add instead of Ionic plugin add? Thanks!

**Comment by Kobzol** [comment]
That's the whole error, on repeated runs it prints this:
```
skipping existing file: CDVWKWebViewEngine.h

skipping existing file: CDVWKWebViewEngine.m
skipping existing file: CDVWKWebViewUIDelegate.h

skipping existing file: CDVWKWebViewUIDelegate.m

skipping existing file: xhr.js

skipping existing file: ios-wkwebview-exec.js

skipping existing file: .gitignore

skipping existing file: CDVWKWebViewEngineTest.m

skipping existing file: Info.plist

skipping existing file: project.pbxproj

skipping existing file: contents.xcworkspacedata

skipping existing file: CDVWKWebViewEngineTest.xccheckout

skipping existing file: CDVWKWebViewEngineLib.xcscheme

skipping existing file: CDVWKWebViewEngineLibTests.xcscheme
skipping existing file: contents.xcworkspacedata

skipping existing file: CDVWKWebViewEngineTest.xccheckout

skipping existing file: CordovaLib.xcscheme

skipping existing file: README.md
skipping existing file: package.json

skipping existing file: plugin.xml

skipping existing file: tests.js

Error: Unexpected token } in JSON at position 3185
```


The plugin folder appears, so the installation doesn't fail completely.
`cordova plugin add` gives the same result.
Installing ionic-cli 2.0.0 doesn't work (there's already an issue about that on the cli repo https://github.com/driftyco/ionic-cli/issues/1288), but it's just 2.0.0-beta.37 relabeled, if I'm not mistaken, so that shouldn't be the problem.

**Comment by jgw96** [comment]
Interesting, thanks for the info. @manucorporat any ideas on the above? @Kobzol Out of curiosity what version of xcode are you running? Also, on the cli issue, do you normally use `sudo` to install global npm packages?

**Comment by ghenry22** [comment]
In case it helps troubleshooting:

install works ok for me with no errors, I am using the latest ionic@beta as of today.  ionic info for reference, I also updated to the latest version of the ios platform before installing.

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.11.1
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by Kobzol** [comment]
My Xcode version is 7.3.1 Build version 7D1014. I'm indeed using `sudo` to install global npm packages.

**Comment by manucorporat** [comment]
Hi @Kobzol! can you post your `package.json`, `platforms/platforms.json`, `plugins/ios.json`, `fetch.json`?

Cordova CLI always prints terrible error messages.

Can you also try to recreate the whole cordova project? ie. remove `platforms/` and `plugins/`
After that you would have to:
`cordova platform add ios`

and manually add the plugins in case you did not use `--save` previously.
also, you should: `ionic build`

**Comment by Kobzol** [comment]
When I removed the `platforms` and `plugins` directories and manually run `cordova platform add ios`, the plugin installation worked. I already tried it before without success, but I used `ionic state restore` instead of manually adding the platform, that was the only difference AFAIK. But that command is already deprecated and it works now, so this is resolved, thank you for your help :-)

**Comment by manucorporat** [comment]
@Kobzol glad it worked!
With cordova, removing everything is the best solution most of the times haha
