### ISSUE TITLE
Works on emulator - Fails on IOS 9 

### ISSUE THREAD

**Issue by sagivf** [driftyco/cordova-plugin-wkwebview-engine#21]
Not sure but it might have something to do with AJAX calls.

![image](https://cloud.githubusercontent.com/assets/1857466/17838247/0d745936-67d1-11e6-9b23-c473a10fd20f.png)

![image](https://cloud.githubusercontent.com/assets/1857466/17838242/df7b8cc0-67d0-11e6-9101-92d3cd648ece.png)

![image](https://cloud.githubusercontent.com/assets/1857466/17838249/1d00c9e8-67d1-11e6-9330-a5a77ac16cf0.png)

**Comment by manucorporat** [comment]
Remove platforms/ and plugins/ folders and recreate all the cordova files from scratch, also make sure the cordova-plugin-wkwebview-engine points to this repo.

Also, can you copy-paste all the logs? not only the crash.

**Comment by sagivf** [comment]
Thanks @manucorporat got it to work!

The weird think is I was not able to use https://github.com/driftyco/ionic-cli#ionic-state-reset and had to do the following:

1) Had to do this one by one - just removing the plugins with `rm -rf ./plugins` gave out an error (something like: Cordov*/**.m already installed.)
```
ionic platform update ios
ionic plugin save           # creates backup of existing plugins
rm -rf ./plugins            # delete plugins directory
ionic prepare       
```
2)
 install mu previous plugins one by one.

What does `ionic plugin save` do?

**Comment by manucorporat** [comment]
Cordova CLI always fails silently (it is so bad sometimes). Removing everything and start from scratch the best solution most of the times.

> What does ionic plugin save do?

haha I am not sure... I never used it 😞 maybe @jthoms1 knows better, he develops the ionic CLI!

I use to do this:
```
rm -rf plugins
rm -rf platforms
cordova platform add ios@4.2.0
// ^this line also install all the saved plugins
ionic build
```
then I open the Xcode manually

**Comment by manucorporat** [comment]
closing issue! 🎉
