### ISSUE TITLE
[Question] Correctly detect app using WKWebView

### ISSUE THREAD

**Issue by zarko-tg** [driftyco/cordova-plugin-wkwebview-engine#25]
README.md currently states:

An easy way to verify that WKWebView has been installed on iOS is to check if `window.indexedDB` exists.  For example:

```
if (window.indexedDB) {
   console.log("I'm in WKWebView!");
} else {
   console.log("I'm in UIWebView");
}
```

The thing is that window.indexedDB is true on iOS 10 whether an app is using this plugin or not.

Any better way to detect if the app itself is using WKWebView?

**Comment by manucorporat** [comment]
ping @jgw96

**Comment by jgw96** [comment]
@zarko-tg Are you running this test in safari on ios 10 or in a cordova app?

**Comment by zarko-tg** [comment]
@jgw96 cordova/ionic 1.3.x app.

**Comment by jgw96** [comment]
@zarko-tg I am currently working on a method to accurately detect whether an app is running in wkwebview no matter the version of iOS you are using. Thanks!

**Comment by rafapardal** [comment]
Any update about this @jgw96?

**Comment by krishnagopinath** [comment]
I'd like to know about this as well. Thanks! :)
