### ISSUE TITLE
Xcode warnings when displaying PDF using InAppBrowser

### ISSUE THREAD

**Issue by elijnzaad** [driftyco/cordova-plugin-wkwebview-engine#27]
I use the InAppBrowser to display the content of a PDF. Everything works fine and it looks exactly like in UIWebView. However in the Xcode console these messages appear:

```
2016-08-22 17:05:05.355 InspectAndGo[2278:1043666] Setting the WebView's frame to {{0, 0}, {1024, 724}}
2016-08-22 17:05:05.387 InspectAndGo[2278:1043666] THREAD WARNING: ['InAppBrowser'] took '62.119873' ms. Plugin should use a background thread.
objc[2278]: UIPDFPageRenderOperation object 0x13e144930 overreleased while already deallocating; break on objc_overrelease_during_dealloc_error to debug
objc[2278]: UIPDFPageRenderOperation object 0x13e14bdb0 overreleased while already deallocating; break on objc_overrelease_during_dealloc_error to debug
objc[2278]: UIPDFPageRenderOperation object 0x13e14c0f0 overreleased while already deallocating; break on objc_overrelease_during_dealloc_error to debug
objc[2278]: UIPDFPageRenderOperation object 0x13e116700 overreleased while already deallocating; break on objc_overrelease_during_dealloc_error to debug
objc[2278]: UIPDFPageRenderOperation object 0x13cdf8050 overreleased while already deallocating; break on objc_overrelease_during_dealloc_error to debug
```

The messages appear only on opening the PDF, no messages on closing.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Most likely, this just means that the InAppBrowser plugin needs to be updated to work totally smoothly with wkwebview, but I am not entirely sure. @manucorporat Does that sound correct to you?

**Comment by elijnzaad** [comment]
I've installed the latest version, 1.4.0. Would you advise me to post this message to the InAppBrowser guys as well?

**Comment by jgw96** [comment]
@elijnzaad Might not be a bad idea to get them in on the conversation too

**Comment by elijnzaad** [comment]
I've filed an issue with them as well: https://issues.apache.org/jira/browse/CB-11750

**Comment by manucorporat** [comment]
I think we can close this issue here, since it is already tracked in apache's JIRA
