### ISSUE TITLE
Just a big thank you

### ISSUE THREAD

**Issue by Hirbod** [driftyco/cordova-plugin-wkwebview-engine#30]
Sometimes, you just need to say: thank you. Finally someone figured out how to bypass that local XHR problem and you guys did that in such an easy but still powerful way. It just worked out of the box for me and finally I have all the benefits of real 60fps inside my app! 

Only thing I am getting is:

Unknown resource gap:// is beein called.

**Comment by dotNetkow** [comment]
HI @Hirbod - I may have an explanation. Do you have a Content Security Policy set up in your index.html file?  "gap:" relates to PhoneGap - I think you'll see that error when the deviceready event fires but you don't include it in the CSP meta tag: (default-src 'self' **gap:**)

`<meta http-equiv="Content-Security-Policy" content="default-src 'self' gap:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; img-src * data:; media-src *;">`

**Comment by Hirbod** [comment]
@dotNetkow Hi, thanks. True, I have this set up. But as far as I know gap:// is important, as cordova creates an Iframe mit src gap://ready. But maybe this is not true for WKWebView

**Comment by dotNetkow** [comment]
ah ok... hmm not sure.  Given you started this issue as a "thank you", you might consider opening a new issue just related to "Unknown resource gap:// is being called."  good luck!
