### ISSUE TITLE
Won't load XHR when URL has parameter

### ISSUE THREAD

**Issue by Hirbod** [driftyco/cordova-plugin-wkwebview-engine#32]
Hi,

to prevent caching, I add ?v=123.. behind my URLs. As soon as I do, it fails to load.

XHR polyfill: (2)
"file not found"
"templates/vehicle_maindata.html?v=13

When I remove ?v=13, it loads the url correctly. Is this something you guys can fix?

**Comment by seme1** [comment]
I am also facing a similar problem. However, the parameters are added to load specific pages on purpose. For instance, "templates/vehicle_data.html?vehicleId=344" should keep the vehicleId paramter as it would be interpreted and routed by Framework7  (the framework I'm using with my app).

**Comment by seme1** [comment]
I have everything working fine in my app (so far) except for this, which is a major issue since many links in my app rely on the parameter passed along with the URL. It would be very much appreciated if this can be fixed as it is the only thing preventing me from publishing my app.

**Comment by seme1** [comment]
I think I discovered the problem causing this. When URL strings are encoded, the question mark at the end of the url gets transformed into another weird character. 
To solve this problem, I think there should be a check for whether the url contains parameters or not (by checking the ?). If there is a ? , it should be removed and saved in a temporary variable. After encoding the URL, the parameter string along with the question mark should be appended again to the URL string.

**Comment by seme1** [comment]
I don't know how to make a pull request as I don't use github. However, this gist file contains a fix for the problem I faced. Simply, swap the original file with this one. 
It would be apprecited if this can be merged with the main repository.

https://gist.github.com/seme1/dc10fab7d789bf7cfbc996735fc261f0
