### ISSUE TITLE
Is it possible to intercept / handle requests for paths outside app root?

### ISSUE THREAD

**Issue by ghenry22** [driftyco/cordova-plugin-wkwebview-engine#33]
It would be great if there was a way for this plugin to intercept requests to standard paths outside of the application root so that they can be used in wkwebview.

For example my app downloads files which should be persistent and not wiped by the OS to cordova.file.datadirectory using the filetransfer plugin and the file plugin.  I then want to display images from this path within the app, or play video / sound files from these paths within the app.

I can save the files here with no problem, and I can check that they exist using the file plugin.

What I can't do is display an image from the datadirectory when using this wkwebview plugin.  It just gets an error.  It doesn't seem like these requests are being intercepted even though they are starting with file: protocol.

If I drop by to uiwebview or test on android everything works so all my paths etc are working and files are present and accounted for.

Given that the file plugin CAN read the files from the file system would it be possible to implement an interceptor for requests to these common local storage paths? Perhaps it could be intercepted and routed to the file plugin to fulfill rather than just trying to load from the local filesystem?

If I have just missed something and this should already be possible please let me know.

**Comment by PapyElGringo** [comment]
We have the same issue here but not on all devices and not every time.
We download images in our device storage and when we try to display them as image source we strangely achieve display the image on some device on sometimes we get the same error as you.
You can use a workaround with the file plugin:
window.resolveLocalFileSystemURL fileUrl, (fileEntry) ->
          fileEntry.file (file) ->
            reader = new FileReader()
            reader.onloadend = ()->
              blob = new Blob([new Uint8Array(@result)], { type: 'image/'+fileExtension })
              //the blob file will be valid you can then make a blob url
              var blobUrl = URL.createObjectURL(blob);
            reader.readAsArrayBuffer(file)

**Comment by pcrombach** [comment]
Ik have the same problem. I use a lot files stem for offline use. IMHO intercepting request to avoid CORS problems should skip all file: requests to FileSystem dirs

**Comment by ghenry22** [comment]
This could be an optional solution.

Add the cordova labs local web server (which they use with the wkwebview platform for only ios versions)

Use it only for access to local file storage outside of app root though.

Intercept file:// requests bound for defined cordova file system locations (ie datadirectory) and simply strip the file:/// on the way through as in the commit below.  This would make it seemless for the user and there would be no need for platform specific file access handling within the users app code as the plugin would handle it.

https://github.com/Switch168/cordova-plugins/commit/f9f9127fc8c8ec03973974097990058669b9bd9a

**Comment by manucorporat** [comment]
@ghenry22  I am thinking of some kind of whitelist of paths... thinking

does this work in UIWebView?

**Comment by ghenry22** [comment]
@manucorporat  access directly to file paths or using cdvfile URLs works fine in uiwebview but not in wk.  If you took something like the minimal web server implementation for accessing paths outside of application root that would be able to work on both UI and wk and android so you could just leave the local webserver installed and never have to adjust your for a specific platform or engine.

The telerik wk web view plugin had something similar where you could just specify /documents for example and the polyfill would catch know paths and redirect to the local webserver without the user having to even really be aware.

Happy to help you with test and feedback as always

**Comment by bmcharg** [comment]
Is there any update on this? I could really do with being to access images and videos from the Documents directory rather than app path, but can't seem to find a way to get it working with the plugin enabled.

**Comment by auggernaut** [comment]
We're in a similar situation... we want to use cordova-file-cache to cache our images, which it stores in /Documents not /www. This is a fairly common use case, odd that I'm having so much trouble finding a solution. Any help is much appreciated!

**Comment by bmcharg** [comment]
One odd thing I've noticed is that I seem to be able to load video files from /Documents using a file:// path, but not images. Any particular reason why that might be the case, and does it suggest some type of workaround to access images too?
