### ISSUE TITLE
Prevent InAppBrowser from blocking WKWebView thread

### ISSUE THREAD

**Issue by dotNetkow** [driftyco/cordova-plugin-wkwebview-engine#37]
Hello! This has been [documented here](https://github.com/apache/cordova-plugin-inappbrowser/pull/162) on the main plugin but thought I'd see if the Ionic team would like to review, given how quickly you've taken to other issues! Someone already wrote a PR, too.

Developers typically use the InAppBrowser plugin (cordova-plugin-inappbrowser, v1.4.0) for authenticating users via OAuth etc.  When the browser is launched in an app using WKWebView though, code from the app is blocked.  Result of this is that the browser can not be closed programmatically.  

Code:
```
var inAppBrowserRef = cordova.InAppBrowser.open("https://google.com", '_blank', 'location=no,toolbar=no,clearcache=yes');
inAppBrowserRef.addEventListener('loadstop', function(event) {

	// Watch for specific URL. In OAuth flow, typically the one that has the granted access token in it
	if (event.url.indexOf("access_token") > -1) {
		// save it, do other stuff
		
		// Close the InAppBrowser, returning control to main app
		// Blocked here, so browser cannot be closed
		inAppBrowserRef.close();
      }
});

```

**Comment by ThorConzales** [comment]
Same issue here.

**Comment by dotNetkow** [comment]
Hi @richtera - not sure if I'm following you, but I think this may be more related to this issue thread: https://github.com/driftyco/cordova-plugin-wkwebview-engine/issues/3.  Check that one out if you haven't already.

**Comment by richtera** [comment]
Possibly related yes. My initial thought was that this plugin somehow changes or affects the inappbrowser plugin. Since auth0 (as an example) uses inappbrowser to be able to redirect to a real https location before attempting to make calls out (i.e. to prevent the CORS error with a file:// url). Removing this plugin reverts the inappbrowser to work normally. But I could be misinterpreting the errors.

**Comment by manucorporat** [comment]
@dotNetkow I would love to fix this issue, but we can't do anything. It has to be fixed in the InAppBrowser plugin

**Comment by dotNetkow** [comment]
Apologies, you are correct!

**Comment by manucorporat** [comment]
@dotNetkow we have decided that this is an important thing for the WKWebView ecosystem and I am working in a fix for InAppBrowser!

**Comment by manucorporat** [comment]
@dotNetkow @richtera @ThorConzales  I forked InAppBrowser and implemented a possible fix:
https://github.com/manucorporat/cordova-plugin-inappbrowser/
Can you try it? and provide feedback?

The PR was also submitted in the official repo:
https://github.com/apache/cordova-plugin-inappbrowser/pull/187

**Comment by dotNetkow** [comment]
Awesome, thanks @manucorporat! You are correct - the fix needed to be in the InAppBrowser plugin - my bad.  I just pulled down your changes and tested them with an app I'm currently building now. iPhone 6, iOS 10.  It works as expected - the "close()" function works now with your changes. In my app, I also load other webpages - those are working well too.  Many thanks!

Should I close this now?

**Comment by manucorporat** [comment]
Glad it worked out! closing! now it's time for the cordova team to review and merge the change

**Comment by AdrienDC** [comment]
Hi @manucorporat ,
on my side it doesn't work with ng-cordova-oauth...

Any idea why?

**Comment by AdrienDC** [comment]
Hi @manucorporat ,
I got an issue with it and ng-cordova-oauth, see #51
