### ISSUE TITLE
input field cursor moves with scrolling(if scrolled on top then cursor ovelaps with header and moves to top)

### ISSUE THREAD

**Issue by mashah1** [driftyco/cordova-plugin-wkwebview-engine#41]
I am using WKWebView but still this is issue is there.
![simulator screen shot 30 aug 2016 3 47 29 p m](https://cloud.githubusercontent.com/assets/17705358/18179221/43e7a672-7036-11e6-8da9-cbca1763b48e.png)

**Comment by danielcrk-cn** [comment]
I thought (and hoped) for sure that this would be fixed in WKWebView as I've been seeing this issue in the old webview for ages now :(

**Comment by ddolheguy** [comment]
Yep this has been an issue for a long time now and I too was hoping it might be fixed ;(

**Comment by manucorporat** [comment]
You can find some workarounds here, but this is a bug that only apple and the webkit team can fix :(

http://stackoverflow.com/questions/20737503/mobile-safari-input-caret-does-not-scroll-along-with-overflow-scrolling-touch

@adamdbradley should ionic implement the hacks above in the framework?
