### ISSUE TITLE
Mailto and tel links are not handled

### ISSUE THREAD

**Issue by danielcrk-cn** [driftyco/cordova-plugin-wkwebview-engine#44]
Even if target="_blank" is included, nothing happens when they are clicked.

**Comment by manucorporat** [comment]
@shazron do you we should support this?
http://stackoverflow.com/questions/26501172/launching-phone-email-map-links-in-wkwebview

**Comment by manucorporat** [comment]
@shazron never mind
@danielcrk-cn fixed!

**Comment by danielcrk-cn** [comment]
@manucorporat, do you know when the fix will be available?

**Comment by manucorporat** [comment]
it is already available. Just reinstall it!

**Comment by shazron** [comment]
Actually this is incorrect. To allow `tel:` you would have an <allow-intent> tag in your config.xml and allow the `tel:` scheme. <allow-intent> will send the URL to the system to open, in this case, the Phone app. I believe it is similar for `mailto:`. Tel and mailto are also special schemes where the webview will handle this automatically if navigated to (ie call the system to handle the url) if you add it in <allow-navigation> as well. If both tags are specified for the same url however, only the <allow-navigation> is considered. 

This should be mostly covered in the cordova-plugin-whitelist docs. I cover the tel: scheme in the tests for the Cordova wkwebview-engine plugin: https://github.com/apache/cordova-ios/commit/3bda0ef487f204e60def4ff1ecf844862460313e

The cordova-ios platform comes with a private plugin that handles these two types of tags: https://github.com/apache/cordova-ios/tree/master/CordovaLib/Classes/Private/Plugins/CDVIntentAndNavigationFilter

**Comment by danielcrk-cn** [comment]
That was the issue, i had set the persmissions (see below) in config.xml and it worked just fine UIWebView but not in WKWebView. Now, after this fix, it works as expected.

```
    <allow-navigation href="mailto:*" />
    <allow-navigation href="tel:*" />
    <allow-intent href="tel:*" />
    <allow-intent href="mailto:*" />
```

**Comment by shazron** [comment]
@danielcrk-cn that's strange, I'll verify your findings and file an issue on issues.cordova.io if verified. thanks!

**Comment by manucorporat** [comment]
@shazron I verified it by myself, cordova allows the request, but it WK does nothing

**Comment by shazron** [comment]
I've tested this, and I can't repro. The anchor links work perfectly on `cordova-wkwebview-engine@1.0.3` and `cordova-ios@4.2.1`

I created a blank new Cordova project, and modified the default `index.html` with these anchor links:
```
    <body>
        <div class="app">
            <h1>Apache Cordova</h1>
            <div id="deviceready" class="blink">
                <p class="event listening">Connecting to Device</p>
                <p class="event received">Device is Ready</p>
                <a href="mailto:name@example.com">MAILTO ME</a><br />
                <a href="tel:15555555">TELTO ME</a><br />
            </div>
        </div>
        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript" src="js/index.js"></script>
    </body>
```

Then I launched onto a device, then clicked on the links. mailto launched the Mail.app, and tel launched the Phone.app.

The `config.xml` had these lines:
```
    <allow-intent href="tel:*" />
    <allow-intent href="mailto:*" />
```
Am I missing something in any of your repro steps?

**Comment by manucorporat** [comment]
@shazron I can't get it to work without this change, it looks like an internal WKWebView thing.

Even though, cordova is allowing the "request" by calling `decisionHandler(WKNavigationActionPolicyAllow)`, WKWebView does nothing.

Are you testing against file: or http:? it is probably a file-only bug, so using a HTTP server it works as expected but from a local file it does not.

**Comment by shazron** [comment]
I tested it using a new Cordova project, so file:// protocol. Like I said, no repro using those exact steps, using vanilla Cordova (no Ionic) and only those two plugins.
