### ISSUE TITLE
Blank page after splash page

### ISSUE THREAD

**Issue by raducostea** [driftyco/cordova-plugin-wkwebview-engine#47]
After the splash page i get a white screen. This is my log

> 2016-09-11 14:03:24.962 Roids[6889:3679029] Apache Cordova native platform version 4.2.1 is starting.
>         2016-09-11 14:03:24.963 Roids[6889:3679029] Multi-tasking -> Device: YES, App: YES
>         2016-09-11 14:03:25.037 Roids[6889:3679029] CDVWKWebViewEngine: trying to inject XHR polyfill
>         2016-09-11 14:03:25.054 Roids[6889:3679029] CDVWKWebViewEngine will reload WKWebView if required on resume
>         2016-09-11 14:03:25.055 Roids[6889:3679029] Using WKWebView
>         2016-09-11 14:03:25.055 Roids[6889:3679029] [CDVTimer][handleopenurl] 0.120997ms
>         2016-09-11 14:03:25.058 Roids[6889:3679029] [CDVTimer][intentandnavigationfilter] 2.875030ms
>         2016-09-11 14:03:25.058 Roids[6889:3679029] [CDVTimer][gesturehandler] 0.122011ms
>         2016-09-11 14:03:25.074 Roids[6889:3679029] [CDVTimer][splashscreen] 15.367985ms
>         2016-09-11 14:03:25.088 Roids[6889:3679029] [CDVTimer][statusbar] 14.270961ms
>         2016-09-11 14:03:25.090 Roids[6889:3679029] [CDVTimer][keyboard] 1.357973ms
>         2016-09-11 14:03:25.090 Roids[6889:3679029] [CDVTimer][TotalPluginStartup] 35.274029ms
>         2016-09-11 14:03:25.102 Roids[6889:3679029] createNotificationChecker
>         2016-09-11 14:03:25.102 Roids[6889:3679029] not coldstart
>         2016-09-11 14:03:25.104 Roids[6889:3679029] active
>         2016-09-11 14:03:25.104 Roids[6889:3679029] PushPlugin skip clear badge
>         2016-09-11 14:03:27.298 Roids[6889:3679029] DEVICE READY FIRED AFTER 1349 ms

Looks like the app is not firing.

**Comment by manucorporat** [comment]
@raducostea can you remote debug it with the safari webtools? it would be really useful to see the logs from the JS side

**Comment by raducostea** [comment]
@manucorporat,

I have no idea how to do that. If you can give me a documentation how i can do that it will be great.

**Comment by manucorporat** [comment]
@raducostea I hope this is helpful: http://phonegap-tips.com/articles/debugging-ios-phonegap-apps-with-safaris-web-inspector.html

**Comment by raducostea** [comment]
Now i am getting something different after removing plugins and platforms folder and reinstalling with ionic platforms add ios.

> 2016-09-13 10:38:06.727 Roids[7515:3986201] Apache Cordova native platform version 4.2.1 is starting.
> 2016-09-13 10:38:06.729 Roids[7515:3986201] Multi-tasking -> Device: YES, App: YES
> 2016-09-13 10:38:06.841 Roids[7515:3986201] CDVWKWebViewEngine: trying to inject XHR polyfill
> 2016-09-13 10:38:06.853 Roids[7515:3986201] CDVWKWebViewEngine will reload WKWebView if required on resume
> 2016-09-13 10:38:06.853 Roids[7515:3986201] Using WKWebView
> 2016-09-13 10:38:06.853 Roids[7515:3986201] [CDVTimer][handleopenurl] 0.126958ms
> 2016-09-13 10:38:06.858 Roids[7515:3986201] [CDVTimer][intentandnavigationfilter] 4.449010ms
> 2016-09-13 10:38:06.858 Roids[7515:3986201] [CDVTimer][gesturehandler] 0.117958ms
> 2016-09-13 10:38:06.868 Roids[7515:3986201] [CDVTimer][splashscreen] 9.783030ms
> 2016-09-13 10:38:06.890 Roids[7515:3986201] [CDVTimer][statusbar] 21.454990ms
> 2016-09-13 10:38:06.892 Roids[7515:3986201] [CDVTimer][keyboard] 1.716971ms
> 2016-09-13 10:38:06.892 Roids[7515:3986201] [CDVTimer][TotalPluginStartup] 38.839996ms
> 2016-09-13 10:38:06.906 Roids[7515:3986201] createNotificationChecker
> 2016-09-13 10:38:06.909 Roids[7515:3986201] not coldstart
> 2016-09-13 10:38:06.912 Roids[7515:3986201] active
> 2016-09-13 10:38:06.912 Roids[7515:3986201] PushPlugin skip clear badge
> 2016-09-13 10:38:08.307 Roids[7515:3986201] DEVICE READY FIRED AFTER 249 ms
> 2016-09-13 10:38:09.651 Roids[7515:3986201] EXCEPTION: Error: Uncaught (in promise): Error: SecurityError: DOM Exception 18
> 2016-09-13 10:38:09.655 Roids[7515:3986201] ERROR: EXCEPTION: Error: Uncaught (in promise): Error: SecurityError: DOM Exception 18
> 2016-09-13 10:38:09.656 Roids[7515:3986201] ERROR: STACKTRACE:
> 2016-09-13 10:38:09.656 Roids[7515:3986201] ERROR: resolvePromise@file:///var/containers/Bundle/Application/28E5493E-9B26-49E1-9711-83843CFEFB98/Roids.app/www/build/js/zone.js:538:41
> file:///var/containers/Bundle/Application/28E5493E-9B26-49E1-9711-83843CFEFB98/Roids.app/www/build/js/zone.js:574:32
> invokeTask@file:///var/containers/Bundle/Application/28E5493E-9B26-49E1-9711-83843CFEFB98/Roids.app/www/build/js/zone.js:356:43
> onInvokeTask@file:///var/containers/Bundle/Application/28E5493E-9B26-49E1-9711-83843CFEFB98/Roids.app/www/build/js/app.bundle.js:39562:51
> invokeTask@file:///var/containers/Bundle/Application/28E5493E-9B26-49E1-9711-83843CFEFB98/Roids.app/www/build/js/zone.js:355:55
> runTask@file:///var/containers/Bundle/Application/28E5493E-9B26-49E1-9711-83843CFEFB98/Roids.app/www/build/js/zone.js:256:58
> drainMicroTaskQueue@file:///var/containers/Bundle/Application/28E5493E-9B26-49E1-9711-83843CFEFB98/Roids.app/www/build/js/zone.js:474:43
> g@file:///var/containers/Bundle/Application/28E5493E-9B26-49E1-9711-83843CFEFB98/Roids.app/www/build/js/es6-shim.min.js:11:1440
> file:///var/containers/Bundle/Application/28E5493E-9B26-49E1-9711-83843CFEFB98/Roids.app/www/build/js/es6-shim.min.js:11:1370
> promiseReactionJob@[native code]
> 2016-09-13 10:38:09.657 Roids[7515:3986201] ERROR: Unhandled Promise rejection: SecurityError: DOM Exception 18 ; Zone: angular ; Task: Promise.then ; Value: Error: SecurityError: DOM Exception 18
> 2016-09-13 10:38:09.657 Roids[7515:3986201] ERROR: error JSON.stringify()ing argument: TypeError: JSON.stringify cannot serialize cyclic structures.
> 2016-09-13 10:38:25.885 Roids[7515:3986201] WARN: Native: deviceready did not fire within 2000ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins/ and reinstalling them.
> 2016-09-13 10:38:25.885 Roids[7515:3986201] DEVICE READY FIRED AFTER 2348 ms

I am using SqlStorage right in the beginning of the initialization. Could that be an issue?

Same errors are present inside the Safari debugger.

**Comment by manucorporat** [comment]
Yes, websql is not supported by WKWebView, you should use a cordova plugin in order to use it in a hybrid app, or migrate to a different DB like pouchDB.

I can't help you without more information.
```
[Debug] XHR polyfill: injected! (user-script:1, line 237)
[Log] DEVICE READY FIRED AFTER (2) (console-via-logger.js, line 173)
```
 is not enough to scope the problem.

Can you provide a whole repo that reproduces the issue?

**Comment by raducostea** [comment]
I think having code before the platform.ready() its an issue. I've moved my code to platform.ready() and the app started but the performance is rather worst. Anyway, this is not actually an issue, i was not using it properly. I will close it. Thanks for all your help.

**Comment by manucorporat** [comment]
@raducostea "the performance is rather worst" what do you mean? it might be an issue
WKWebview should be much faster (startup is still a work in progress)

**Comment by raducostea** [comment]
For example when i change pages the transition of the page is not running smoothly or i don't see it at all. It just shows the page without any transitions. I have a rather big app and its private so i can't share any code.
