### ISSUE TITLE
iFrame 3rd party script cannot execute parent callback (Braintree dropin UI) 

### ISSUE THREAD

**Issue by growthclick** [driftyco/cordova-plugin-wkwebview-engine#48]
Working with Braintree's iframe-based ecommerce drop-in UI, the Braintree code was not able to execute a callback function in the parent Ionic code. This worked fine in UI Web View, but with WKWebView, the iFrame content rendered (e.g. Braintree form), but the braintree scripts were not able to execute any parent code, and there was no console error.  

The first callback is related to an "OnReady" event, once the iframe Braintree form has rendered, but it isn't being executed, which might suggest this is more than a CORS issue. The background on Braintree is here: https://developers.braintreepayments.com/reference/client-reference/javascript/v2/best-practices

Code snippet of the Braintree callback is below, and we've tried it with CORS enabled and disabled in the API call. We've got all the braintree content security policy tags in place, the config.xml white listing (access-origin, allow-intent, allow-navigation to *), and the cordova white list plugin in place. 

```
 braintree.setup(vm.clientToken, "dropin", {
                container: "payment-form",
                enableCORS: true,
                onPaymentMethodReceived: function (btResponse) {
                    $scope.submitPayment(btResponse);
                },
                onReady: function (integration) {
                    $log.debug("prepareOrder.onReady is firing ");
                    $scope.checkout = integration;
                    $scope.tokenStatus.received = "yes";
                    $scope.showPaymentButtons();
                    $scope.$apply();
                },
                onError: function (err) {
                    $log.error("Error: ");
                    $log.error(err);
                }
            });

```
For now we're reverting back to UIWebView, but would love to upgrade to WKWebView. Appreciate any advice on how to overcome this issue. Thanks

**Comment by manucorporat** [comment]
I just pushed a small change to this plugin, can you update and try again?

**Comment by growthclick** [comment]
Thanks. I grabbed the latest version from master using the install instructions but the callback code is still inaccessible from the iframe script.

**Comment by growthclick** [comment]
I noticed you closed this - was this issue fixed through a new build or is this duplicate? Thanks
