### ISSUE TITLE
Xcode error: XHR polyfill was not found!

### ISSUE THREAD

**Issue by iAn-Pinto** [driftyco/cordova-plugin-wkwebview-engine#5]
After installing cordova-plugin-wkwebview-engine and running the app on an iPhone through XCode, the following error was generated:

> Xcode error: XHR polyfill was not found!

Line of code affected:
`[userContentController addUserScript:[self xhrPolyfillScript]];`

**Comment by manucorporat** [comment]
@iAn-Pinto thanks for the report!
there should be a `xhr.js` in the Xcode project inside www.

It is difficult to diagnose your problem without more information:
- Cordova CLI may failed silently and did not imported the xhr.js file
- It might be a bug in `[self xhrPolyfillScript]`

Could you try to rebuild the whole cordova project? ie. remove the platforms/ and plugins/ folders and recreate them again?

**Comment by manucorporat** [comment]
@iAn-Pinto is it working for you?

**Comment by iAn-Pinto** [comment]
I retried and now the error is not generated, but a CORS issue is preventing me to login to my app server.

**Comment by jgw96** [comment]
Hello @iAn-Pinto ! Most likely this is caused by cors not being set up correctly on your server. Can you confirm that your server is sending the correct headers etc for a proper cors setup?

**Comment by chauthai** [comment]
I stumbled on the same problem with CORS and found this solution on Stackoverflow:
http://stackoverflow.com/questions/36000757/cordova-ios-error-origin-null-is-not-allowed-by-access-control-allow-origin
