### ISSUE TITLE
App Pause and Resume events are not fired (maybe not even happening?)

### ISSUE THREAD

**Issue by NorthMcCormick** [driftyco/cordova-plugin-wkwebview-engine#52]
Hey team,

My app has a built in timer that heavily relies on the app pause/resume events for proper functionality. Essentially when the app hits the background and comes back to the foreground the timer does some calculations and adjusts itself accordingly. 

This may be a "Solving for Y when the problem is X" kind of bug so I'm open to discussion on ways to improve the question.

I've wired up the pause/resume events like so

```
$ionicPlatform.ready(function() {

		//$scope.modals.shakeFeedbackWarning.show();
		//$scope.modals.shakeFeedback.show();

		// device APIs are available
		//
		function onDeviceReady() {
		    document.addEventListener("pause", onPause, false);
		    document.addEventListener("resume", onResume, false);
		    // Add similar listeners for other events
		}

		function onPause() {
		    // Handle the pause event
		    console.log('PAUSING');
		}

		function onResume() {
		    // Handle the resume event
		    console.log('RESUMING');
		}

		onDeviceReady();
});
```

Update: I had a bug somewhere else in my code preventing the logs from working however I have narrowed down the issue a little more. The app's Pause and Resume events ARE firing, but the app isn't pausing. So I'm getting told that "Hey your app just hit background, and your timer should have stopped at this point" but the timer still runs, and when my app comes back into the foreground, it has elapsed X seconds and then gets set X seconds less (essentially double what it should).

So two potential solutions? (I haven't worked with the WKWebView native side this is just me brainstorming) 1) Add two new events like 'stopped' and 'started' that fire when the app actually stops 'working' and when it is able to start working again. 2) Actually force the WKWebView to stop doing things when the pause event is fired. 

Sorry if this seems scattered I'm still trying to fully understand what is and isn't working but thought I'd get the ball rolling.

**Comment by manucorporat** [comment]
@NorthMcCormick 
- These events are cordova events, their implementation details are not provided by this plugin, and this plugin should not provide additional (no standard events).

https://cordova.apache.org/docs/en/5.1.1/cordova/events/events.html

- WKWebView features an out-of-process architecture that might can continue running when the app is in the background.

- WKWebView does not provide an API to stop any kind of rendering/js execution.

> "Hey your app just hit background, and your timer should have stopped at this point"

That assumption is not right, you should not rely in pause/resume as a source of trust.
But instead use the pause/resume callbacks to stop your timer implicitly.
