### ISSUE TITLE
Intercepted XHR does not trigger change detection

### ISSUE THREAD

**Issue by biesbjerg** [driftyco/cordova-plugin-wkwebview-engine#78]
I'm fetching a local json file and find that I have to manually trigger change detection.

```
public findAll(): Observable<ShopInterface[]> {
	return this._http
		.get('assets/data/shops.json')
		.map(response => response.json().data.map(data => shopFactory(data)));
}
```

XCode log looks fine, I think:

```
2016-11-18 18:43:25.886080 Mindly[5624:1591535] CDVWKWebViewEngine: XHR intercepted: assets/data/shops.json
```

- The same code is working in UIWebView. 
- Change detection runs when fetching the same file from a remote server (with the appropiate CORS headers set).

EDIT:
I managed to reproduce the bug in a starter:

https://github.com/biesbjerg/xhr-wkwebview

**Comment by biesbjerg** [comment]
FYI, checked if this pull request somehow fixed the issue: https://github.com/driftyco/cordova-plugin-wkwebview-engine/pull/70

Sadly, it did not.

**Comment by Bouzmine** [comment]
+1

**Comment by biesbjerg** [comment]
Thanks! It's working now :)

**Comment by manucorporat** [comment]
@biesbjerg awesome! It was an critical bug
