### ISSUE TITLE
Inertial scroll blocks anything on screen from receiving taps

### ISSUE THREAD

**Issue by biesbjerg** [driftyco/cordova-plugin-wkwebview-engine#79]
When flick scrolling (inertial scroll) the page doesn't receive tap events until scrolling has come to a complete stop. That means you can't change tabs, click buttons on the screen etc.

This is possible in native apps and using standard UIWebview.

**Comment by manucorporat** [comment]
I am aware of this issue, it is in our roadmap to find a solution

**Comment by manucorporat** [comment]
This was already fixed!
