### ISSUE TITLE
sqlite support

### ISSUE THREAD

**Issue by mnewmedia** [driftyco/cordova-plugin-wkwebview-engine#8]
As you can see my avatar i'm a pouchdb fan ;) So i need websql support with unlimited storage.
That's why Nolan Lawson wrote the plugin [cordova-plugin-sqlite-2](https://github.com/nolanlawson/cordova-plugin-sqlite-2) he also said it would work in wkwebview.
But it doesn't work anymore when using this wkwebview plugin. I also tried using more general but slower [cordova-sqlite-storage](https://github.com/litehelpers/Cordova-sqlite-storage) but also did not work.

**Comment by manucorporat** [comment]
@mnewmedia hi!
Can you verify it does work with https://github.com/apache/cordova-plugin-wkwebview-engine?

If you used another wkwebview plugin before, sometimes cordova CLI does strange things. Can you try to recreate the cordova project from scratch? i.e. remove platforms/ and plugins/ folders.

**Comment by mnewmedia** [comment]
I never used the `official wkwebview` before, but the creator of `cordova-plugin-sqlite-2` said it works.

I tried the`official wkwebview` just now and just got a blank white screen.
I also tried again`ionic/wkwebview` with removing plugins and platform but got the same error `adapter missing` form pouchdb.

**Comment by jgw96** [comment]
Hello @mnewmedia ! Would you be able to post the exact error you are getting? Thanks!

**Comment by mnewmedia** [comment]
Just *adapter missing* this error comes from pouchdb. I did not see any other errors. Pouchdb looks just if websql is supported and if not it trows *adapter missing*.

**Comment by mlynch** [comment]
Just so we're clear, WebSQL is no longer supported in WKWebView, so that won't work. However, the sqlite fallback should work, and I've heard folks say that nolan's plugin works, so perhaps we should bake it into our storage system...I'll look into that on the v2 and native side and let me know what you guys figure out on the plugin side

**Comment by ozexpert** [comment]
cordova-plugin-sqlite2 works charm. It's just the pouchDB doesn't work for local with sqlite. 

I get this when i try to call `new PouchDB('dbname', {adapter: 'websql'})`
```
ERROR: WebSQL threw an error Error: Error code 14: unable to open database file
```
the thing is that defining adapter as 'websql' will use sqlite plugin first not websql. 
http://gonehybrid.com/how-to-use-pouchdb-sqlite-for-local-storage-in-your-ionic-app/

also is mentioned in PouchDB document. 
https://pouchdb.com/api.html#create_database

**Comment by mlynch** [comment]
@ozexpert is it possible to specify sqlite specifically in the adapter settings instead of relying on the websql fallback? At any rate, it's clear this is a PouchDB bug with WKWebView

**Comment by ozexpert** [comment]
@mlynch that i would have to ask the creator of PouchDB, 
using sqlite2 plugin, i have no problem opening db and reading/writing.

just that when i use pouchdb to open a local db, it seems to be trying to use WebSQL not sqlite.

**Comment by mnewmedia** [comment]
opened a issue at [pouchdb](https://github.com/pouchdb/pouchdb/issues/5579).

**Comment by mnewmedia** [comment]
Just use this plugin and it will work fine again [pouchdb-adapter-cordova-sqlite](https://github.com/nolanlawson/pouchdb-adapter-cordova-sqlite). But syncing a big database is like 25% slower. But in UIWebview the memory did grow 75mb while syncing, with this plugin just 2mb which will get cleaned up again.

**Comment by htejwani** [comment]
Hi mnewmedia, I tried using WKWebview and pouchdb-adapter-cordova-sqlite with cordova-sqlite-plugin 2 in my ionic app. The app still crashes, the memory you see in Xcode does not go up, but the memory does actually rise, you can see  the memory consumed by other processes going up. I do see a memory warning after a few video attachments get downloaded and the app does finally crash. FYI - I am trying to sync  a database with 10 video files of 30MB each. 

Can you please let me know if you are trying something different?

**Comment by mnewmedia** [comment]
Sorry, i don't think i can help you in this case that much. But I for sure would not use pouchdb to sync video files. Why not just download them and store them with the `cordova-file-plugin`?

**Comment by CatchSandeepVaid** [comment]
I have a similar requirement of syncing video files between pouchdb and couchdb. 
**mnewmedia** - Are u suggesting that one should put videos in say app directory using cordova-file-plugin and then implement our own strategy for syncing videos?

I see few issues with this approach:
1. Ideally syncing (video) stuff should be handled by pouchdb, thats what it is built for. Moreover implementing our own strategy for syncing video is a big effort.
2. By keeping docs and videos unrelated, when we sync, it may happen that we get the document but not its video due to internet disconnection in between. So we need to take care of many situations.

**Comment by mnewmedia** [comment]
Yes that's what i meant. 
If this doesn't work for you there are only 2 things you can do:
- Else try if it works with other `sqlite-plugins` there are like 3 of them. 
- Find out what/which repo is causing the crash and open an issue there with as much details as possible.
