### ISSUE TITLE
Rendering of the big list is slow on scrolling.

### ISSUE THREAD

**Issue by alexandrzavalii** [driftyco/cordova-plugin-wkwebview-engine#81]
After installing wkwebview, the lagging scrolling of the list was fixed.
However the list now is not rendering fast enough, and I can see a broken list for a second before it shows up.
Anyone faced same issues?

**Comment by vswom** [comment]
Yes I have the same problem.  I have a list of 2000 data and I can see a broken list for a second before it shows up.

**Comment by manucorporat** [comment]
This plugin only uses the WebKit browser provided by Apple, we can't fix the WK engine itself. If you feel this could be improved by using different CSS properties, HTML or JS. Please resubmit this issue in the framework's repo. Thanks!
