### ISSUE TITLE
After I installed the plugin, this.app.setScrollDisabled(true) disables my whole page.

### ISSUE THREAD

**Issue by alexandrzavalii** [driftyco/cordova-plugin-wkwebview-engine#82]
I am using ionic2 and in lifeevents I have this:
`    ionViewWillEnter() {
        this.app.setScrollDisabled(true);
    }`
However the form on this page and all the buttons are disabled. Basically I cannot do anything, only kill the app. 
Is this a bug ? Or I should use a different method for wkwebview engine ?

**Comment by manucorporat** [comment]
@alexandrzavalii `setScrollDisabled()` is a private API, you should not use.

What do you want to do?

**Comment by alexandrzavalii** [comment]
@manucorporat I want to disable scroll on the login page.

**Comment by alexandrzavalii** [comment]
@manucorporat alright I have added .css class in this page. 
`  .scroll-content {
    overflow-y: hidden;
  }`

**Comment by manucorporat** [comment]
@alexandrzavalii  so, you want to disable the bouncing, right?

**Comment by alexandrzavalii** [comment]
@manucorporat  yeah , it wasnt the issue of wkwebview.
After I updated ionic to latest version. this.app.setScrollDisabled(true); was breaking my application.

**Comment by manucorporat** [comment]
@alexandrzavalii try this:
```
<ion-content no-bounce>

<ion-content>
```
