### ISSUE TITLE
iFrame XHR 'Context not found'

### ISSUE THREAD

**Issue by michaelpeterlee** [driftyco/cordova-plugin-wkwebview-engine#87]
Include xhr.js in iFrame and local resources load 100%

Subsequent XHR requests within iFrame fail with 'Context not found'.

**Comment by manucorporat** [comment]
Can you reinstall WK and try again? WK 2.0 was released!!
https://github.com/driftyco/cordova-plugin-wkwebview-engine/commit/114a9b190a06285d3ae6ac0384e85e0401942d56

**Comment by michaelpeterlee** [comment]
Awesome work Manu, this has simplified our implementation considerably.

Cannot test our iFrame implementation yet as the following resources no longer exist (existed in prior release):

window.LocalFileSystem
window.requestFileSystem()

**Comment by michaelpeterlee** [comment]
Awesome work Manu, iFrame XHR requests now resolve.
