### ISSUE TITLE
Cordova StatusBar plugin does not move WKWebViews' frame which leads to always overlaying the WebView

### ISSUE THREAD

**Issue by ManuelRauber** [driftyco/cordova-plugin-wkwebview-engine#91]
Howdy,

per default (no cordova-plugin-statusbar installed), the iOS status bar will overlay the WebView, which looks kind of strange:

![image](https://cloud.githubusercontent.com/assets/740791/22185525/e4b43b8e-e0e7-11e6-9d63-3045ecb86361.png)

Normally after installing cordova-plugin-statusbar and changing the setting `StatusBarOverlaysWebView` to false, resizes the WebView so that the status bar is not overlaying it. This does not work with the Ionic's cordova-plugin-wkwebview-engine but does with the original version of the plugin. It should then look like this (no styling applied for this screenshot):

![image](https://cloud.githubusercontent.com/assets/740791/22185589/dfe74334-e0e8-11e6-8f6f-49078fee8d44.png)

It would be great, if your plugin could respond to that cordova-plugin-statusbar :-)

**Comment by ManuelRauber** [comment]
Sorry! I was a bit fast here. The problem is not coming from your adaption of the WkWebView engine but cordova's prepare command not working reliably. I close this issue here.

**Comment by SamDelgado** [comment]
@ManuelRauber how did you fix cordova's prepare command to get this to work? The iOS status bar is overlaying my app after updating some plugins and I am even calling StatusBar.overlaysWebView(false) in my code. The weird thing is it works properly when the app is launched, but after taking a picture and coming back to the app it breaks and looks like your top photo.

**Comment by ManuelRauber** [comment]
@SamDelgado In my case I just called `cordova prepare` twice, since the first one lead to a double definition of `StatusBarOverlaysWebView` within the platform's specific `config.xml`. The second call of `cordova prepare` set it correctly to the value I wanted. 

I reported this issue to cordova as well: https://issues.apache.org/jira/browse/CB-12381

**Comment by SamDelgado** [comment]
@ManuelRauber Thanks for the quick response! I just found that double definition in the iOS `config.xml`. Hopefully things will be all good in my next build.

**Comment by Mr-Anonymous** [comment]
I am having the same issue. I tried running `cardova prepare` plenty of times, the `StatusBarOverlaysWebView` definition is only once in my config.xml. The Status Bar in iOS is overlapped like the first image here since the App is launched. This only happened after adding `wkwebview` plugin to my App. Any other solution I can try?

**Comment by Mr-Anonymous** [comment]
I got the scroll bar issue resolved. What happened in my case is, when I removed and added the ios platform again when I installed this wkwebview plugin, the `cordova-plugin-statusbar` plugin did not get installed for iOS. So I added this plugin again with the `--save` flag and then the status bar issue got resolved.
