### ISSUE TITLE
Upgrade from 1.1.1-dev to 1.1.2-dev breaks html <video>

### ISSUE THREAD

**Issue by SkogDev** [driftyco/cordova-plugin-wkwebview-engine#95]
This bug is IOS and "ionic run ios" only.
Unable to reproduce with "live reload".

Ionic info:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.2.0
Xcode version: Xcode 8.2.1 Build version 8C1002

After some hours of debugging, I finally found the source of my video not playing.
Inline or not, does not matter. 1.1.2-dev will not play this line of code:

```
<video id="video" autoplay loop webkit-playsinline playsinline poster="" class="loginvid">
    <source src="assets/vid/vid.mp4" type="video/mp4">
  </video>
```

To reproduce, clone ionic-conference-app, and run this code with this plugin installed (v.1.1.2-dev).
Then revert back to 1.1.1, which will play the video nicely.

The "`preference name="AllowInlineMediaPlayback" value="true" />`" must be added to the config.xml of course.

**Comment by repetier** [comment]
Thanks for the hint with 1.1.1. Got the same problem with 1.1.2-dev and reverting also helped in my case. So I guess something relevant changed in between.

**Comment by dylanvdmerwe** [comment]
Is this not related? https://github.com/driftyco/cordova-plugin-wkwebview-engine/issues/80

**Comment by repetier** [comment]
Also #80 is bugging me as well (which I solved using local webserver) I don't think it is related. In my case the video file is stored where WKWebview can read the content while in #80 WKWebview does not allow to access files outside www folder. Especially since downgrading helps it shows we are not talking about a WKWebview limitation.

**Comment by michaelpeterlee** [comment]
We use a local device webserver to serve video via <video> successfully.

**Comment by manucorporat** [comment]
@repetier @michaelpeterlee @dylanvdmerwe this should be fixed in the current version, can you try reinstall?

**Comment by michaelpeterlee** [comment]
Works thank you @manucorporat. I had to remove this Cordova plugin a few times for it to update to latest changes. This mitigates documenting GCDWebServer component for us; Just install this plugin!
